main:
  - name: About
    url: /#about
    weight: 10

  - name: Posts
    url: /#posts
    weight: 20

  - name: Publications
    url: /#publications
    weight: 30

  - name: Projects
    url: /#projects
    weight: 40

  - name: Talks
    url: /#talks
    weight: 50

  - name: Newsletter
    url: /#newsletter
    weight: 60